package ru.raidmine.minibaritone;

import net.minecraft.client.MinecraftClient;
import net.minecraft.client.network.ClientPlayerEntity;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.MathHelper;

import java.util.ArrayList;
import java.util.List;

/**
 * Moves the local player along a path generated by PathFinder.
 * It does not break blocks, place blocks, scaffold, swim, fly, or avoid mobs.
 */
public final class Navigator {
    private static final double NODE_REACHED_DISTANCE = 0.55D;
    private static final int REPATH_EVERY_TICKS = 60;
    private static final int MAX_SEARCH_NODES = 14_000;

    private List<BlockPos> path = new ArrayList<>();
    private BlockPos requestedTarget;
    private BlockPos resolvedTarget;
    private int pathIndex;
    private int ticksSinceRepath;
    private boolean running;

    public void goTo(BlockPos target) {
        MinecraftClient client = MinecraftClient.getInstance();
        if (client.player == null || client.world == null) {
            MiniBaritoneClient.send("Мир ещё не загружен.");
            return;
        }

        this.requestedTarget = target;
        if (computePath(client, true)) {
            this.running = true;
            this.ticksSinceRepath = 0;
            MiniBaritoneClient.send("Иду к " + format(target) + ". Точек пути: " + path.size());
        }
    }

    public void tick(MinecraftClient client) {
        if (!running) {
            return;
        }
        if (client.player == null || client.world == null) {
            stopKeys(client);
            running = false;
            return;
        }

        if (path.isEmpty() || pathIndex >= path.size()) {
            stop("Путь завершён.");
            return;
        }

        ticksSinceRepath++;
        if (ticksSinceRepath >= REPATH_EVERY_TICKS) {
            computePath(client, false);
            ticksSinceRepath = 0;
        }

        ClientPlayerEntity player = client.player;
        BlockPos node = path.get(pathIndex);
        double targetX = node.getX() + 0.5D;
        double targetY = node.getY();
        double targetZ = node.getZ() + 0.5D;

        double dx = targetX - player.getX();
        double dz = targetZ - player.getZ();
        double horizontalDistance = Math.sqrt(dx * dx + dz * dz);

        if (horizontalDistance < NODE_REACHED_DISTANCE && Math.abs(player.getY() - targetY) < 1.35D) {
            pathIndex++;
            if (pathIndex >= path.size()) {
                stop("Дошёл до цели " + format(resolvedTarget != null ? resolvedTarget : requestedTarget) + ".");
            }
            return;
        }

        lookAt(player, dx, dz);
        pressMovementKeys(client, player, node, horizontalDistance);
    }

    public void stop(String message) {
        MinecraftClient client = MinecraftClient.getInstance();
        stopKeys(client);
        running = false;
        path.clear();
        pathIndex = 0;
        ticksSinceRepath = 0;
        MiniBaritoneClient.send(message);
    }

    public String getStatusText() {
        if (!running) {
            return "Сейчас не двигаюсь.";
        }
        return "Иду к " + format(requestedTarget) + ", точка " + (pathIndex + 1) + "/" + path.size() + ".";
    }

    private boolean computePath(MinecraftClient client, boolean showErrors) {
        if (client.player == null || client.world == null || requestedTarget == null) {
            return false;
        }

        BlockPos start = client.player.getBlockPos();
        PathFinder.Result result = PathFinder.findPath(client.world, start, requestedTarget, MAX_SEARCH_NODES);
        if (!result.success()) {
            stopKeys(client);
            running = false;
            path.clear();
            pathIndex = 0;
            if (showErrors) {
                MiniBaritoneClient.send(result.message());
            }
            return false;
        }

        this.path = result.path();
        this.resolvedTarget = result.resolvedTarget();
        this.pathIndex = Math.min(1, Math.max(0, path.size() - 1));
        return true;
    }

    private void pressMovementKeys(MinecraftClient client, ClientPlayerEntity player, BlockPos node, double horizontalDistance) {
        stopKeys(client);

        client.options.forwardKey.setPressed(true);
        client.options.sprintKey.setPressed(horizontalDistance > 1.8D);

        int currentY = player.getBlockPos().getY();
        boolean shouldJump = node.getY() > currentY || player.horizontalCollision;
        client.options.jumpKey.setPressed(shouldJump);
    }

    private void stopKeys(MinecraftClient client) {
        if (client == null || client.options == null) {
            return;
        }
        client.options.forwardKey.setPressed(false);
        client.options.backKey.setPressed(false);
        client.options.leftKey.setPressed(false);
        client.options.rightKey.setPressed(false);
        client.options.jumpKey.setPressed(false);
        client.options.sprintKey.setPressed(false);
    }

    private void lookAt(ClientPlayerEntity player, double dx, double dz) {
        if (Math.abs(dx) < 0.0001D && Math.abs(dz) < 0.0001D) {
            return;
        }
        float yaw = (float) (Math.toDegrees(Math.atan2(dz, dx)) - 90.0D);
        player.setYaw(MathHelper.wrapDegrees(yaw));
        player.setPitch(0.0F);
    }

    private String format(BlockPos pos) {
        if (pos == null) {
            return "неизвестно";
        }
        return pos.getX() + " " + pos.getY() + " " + pos.getZ();
    }
}
